// JavaScript Document

document.writeln("<div class=\"ey_zjd\">");
document.writeln("<div class=\"ey_abouts\"><img src=\"http://www.nclaimei.com/expert/images/zj_01.jpg\" /></div>");
document.writeln("<div class=\"ey_list\">");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_2.jpg\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">覃耀锋|</b><b style=\" font-size:28px;\">技术院长</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("南昌莱美美容医院技术院长；<br />");
document.writeln("中国医师协会整形美容分会成员；<br />");
document.writeln("中国修复重建外科学会成员； <br />");
document.writeln("中国十佳青年技术派杰出整形医师； ");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:五官精细化整形<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("360°水动力螺旋吸脂 <br />");
document.writeln("U弧立体美胸<br />");
document.writeln("注射微整形等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_3.png\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">彭圣海|</b><b style=\" font-size:28px;\">技术院长</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("南昌莱美美容医院技术院长；<br />");
document.writeln("中国医师协会美容与整形医师分会会员；<br />");
document.writeln("《中国美容医学》杂志参编者； <br />");
document.writeln("中国十佳青年技术派杰出整形医师； ");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:眼部综合整形<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("鼻部综合整形 <br />");
document.writeln("面部整形等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_sy.png\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">舒寅|</b><b style=\" font-size:28px;\">口腔科主任</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("南昌莱美美容医院口腔科主任；<br />");
document.writeln("国际齿科美容修复联盟会员；<br />");
document.writeln("美国牙医协会（ADA）正式会员； <br />");
document.writeln("德国Gumsmile微创美学修复理事； <br /> ");
document.writeln("德国水晶全瓷牙美容修复专家 ； <br /> ");
document.writeln("天使隐形矫正权威专家； ");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:莱美5D明星美容冠<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("微调隐形正畸 <br />");
document.writeln("牙齿美容性修复等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_7.jpg\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">廖洪越|</b><b style=\" font-size:28px;\">副主任医师</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("南昌莱美美容医院副主任医师；<br />");
document.writeln("医学博士；<br />");
document.writeln("硕士研究生导师；");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:上睑下垂矫正术<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("鼻部综合塑形 <br />");
document.writeln("唇裂二期畸形的整复<br />");
document.writeln("自体脂肪隆胸等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_8.jpg\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">刘波涛|</b><b style=\" font-size:28px;\">皮肤科主任</b>");
document.writeln("<div class=\"ey_zjcj\">");

document.writeln("国内资深皮肤专家<br />");
document.writeln("中国激光美肤实力派代表；<br />");
document.writeln("明星医学美肤私人顾问；<br />");
document.writeln("电视台众多主持人美肤特约顾问 <br />");
document.writeln("韩国首尔整形美容医院合作专家");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");

document.writeln("擅长项目:双核光祛斑；<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("opt王者风范美肤； <br />");
document.writeln("解决各种不良皮肤美容后遗症等； ");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_5.jpg\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">冯宇明|</b><b style=\" font-size:28px;\">皮肤科医师</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("莱美美容医院皮肤科执行医师:<br />");
document.writeln("莱美抗衰老专家；<br />");
document.writeln("中国医师协会美容整形分会会员；<br />");
document.writeln("中国激光美容协会会员");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:面部年轻化；<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("嫩肤美白；<br />");
document.writeln("水光注射；等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");


document.writeln("<div class=\"ey_zj\">");
document.writeln("<div class=\"ey_zjlef\"><img src=\"http://www.nclaimei.com/expert/images/zj_9.jpg\" /> </div>");
document.writeln("<div class=\"ey_zjrin\"><b style=\"font-size:36px; color:;\">龚衍寿|</b><b style=\" font-size:28px;\">个性化无痛整形专家</b>");
document.writeln("<div class=\"ey_zjcj\">");
document.writeln("莱美个性化无痛整形定制学科带头人<br />");
document.writeln("国内首批倡导安全无痛整形专家；<br />");
document.writeln("中华医学会疼痛学会会员；<br />");
document.writeln("中华医学会麻醉学分会会员");
document.writeln("</div>");
document.writeln("<div class=\"ey_zjsc\">");
document.writeln("擅长项目:无痛溶质减肥；<br />");
document.writeln("<div class=\"ey_zjc\">");
document.writeln("双眼皮； <br />");
document.writeln("面部线雕年轻化等");
document.writeln("</div> ");
document.writeln("</div>");
document.writeln("<a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">");
document.writeln("<div class=\"ey_zjim\"><img src=\"http://www.nclaimei.com/expert/images/zj_02.jpg\" /></div></a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");

document.writeln("<div class=\"ey_left\"><img src=\"http://www.nclaimei.com/expert/images/ler_03.jpg\"  /></div>");
document.writeln("<div class=\"ey_ring\"><img src=\"http://www.nclaimei.com/expert/images/ler_05.jpg\" /></div>");
document.writeln("</div>");
