document.writeln("<div class=\"team\">")
document.writeln("</div>")
document.writeln("<div class=\"jdxm\">");
document.writeln("    <div class=\"jdxm-top\"></div>");
document.writeln("    <div class=\"marquee\">");
document.writeln("        <ul>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16ytlx.html\" title=\"玉兔胸\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_01.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16kyj.html\" title=\"开眼角\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_02.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16zhlb.html\" title=\"综合隆鼻\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_03.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16wz.html\" title=\"微整形\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_04.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16qb.html\" title=\"祛斑\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_05.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16mbxd.html\" title=\"线雕\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_06.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/15rlt.html\" title=\"热拉提\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_07.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/16jsm.html\" title=\"极塑美\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_08.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/17dlhf.html\" title=\"冻龄活肤\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_09.jpg\"/></a></li>");
document.writeln("            <li><a href=\"http://www.nccharm.com.cn/special/17sfzqyd.html\" title=\"三分钟祛眼袋\"><img src=\"http://www.nccharm.com.cn/statics/images/zt_10.jpg\"/></a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<script type=\"text/javascript\" src=\"http://www.nccharm.com.cn/phpcms/templates/default/special/15mlbs/js/marquee.js\"></script>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    //经典项目滚动");
document.writeln("    $(document).ready(function(){");
document.writeln("        $(\'.marquee\').kxbdMarquee({");
document.writeln("            direction:\'left\',");
document.writeln("            eventA:\'mouseenter\',");
document.writeln("            eventB:\'mouseleave\'");
document.writeln("        });");
document.writeln("    });");
document.writeln("</script>");
document.writeln("<div class=\"foot\">");
document.writeln("    <div class=\"foot_main\">");
document.writeln("        <ol>");
document.writeln("            <div class=\"foot_logo\"></div>");
document.writeln("            <div class=\"w565\">");
document.writeln("                <ul>");
document.writeln("                    <h6>整形美容</h6>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/xbzx/\" >胸部整形</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/xzjf/\" >吸脂减肥</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/hmzx/\" >面部美容</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/ymzx/\" >眼眉整形</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/bbxz/\" >鼻部整形</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/zhengxing/smzx/\" >私密整形</a></li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <h6>皮肤美容</h6>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/mbnf/\" >美白嫩肤</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/slxqb/\" >赛诺秀祛斑</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/fhcz/\" >复合除皱</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/jgmr/\" >净肤抗敏</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/yjtm/\" >有效脱毛</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/meifu/yshwx/\" >艺术纹绣</a></li>");
document.writeln("                </ul>");
document.writeln("                <ul class=\"w100\">");
document.writeln("                    <h6>微整形美容</h6>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/bls/\" >玻尿酸</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/rds/\" >肉毒素</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/zhushechuzhou/\" >注射除皱</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/tianchong/\" >填充塑形</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/kangshuailao/\" >抗衰老</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/weizhengxing/zhusheshoulian/\" >注射瘦脸</a></li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <h6>口腔美容</h6>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/kouqiang/jiaozheng/\" >牙齿正畸</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/kouqiang/kaociya/\" >牙齿美容</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/kouqiang/meibai/\" >牙齿美白</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/kouqiang/zhongzhi/\" >牙齿种植</a></li>");
document.writeln("                    <li><a href=\"http://www.nccharm.com.cn/kouqiang/huli/\" >口腔护理</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\"qrcode\">");
document.writeln("                <div class=\"qrpic\"></div>");
document.writeln("                <div class=\"intro\">");
document.writeln("                    <p>CHARM 南昌佳美官方微信<br><br>美丽热线：400-679-6066<br>地址：南昌市青云谱区洪都南大道273号<a href=\"/kuaibao/5726.html\" class=\"lydt\" target=\"_blank\"><img src=\"http://www.nccharm.com.cn/statics/images/lydt.jpg\"/></a></p>");
document.writeln("                </div>");
document.writeln("                <div class=\"cl search\">");
document.writeln("                    <form name=\"search\" action=\"http://www.nccharm.com.cn/index.php\" method=\"get\" >");
document.writeln("                        <input type=\"hidden\" name=\"m\" value=\"search\"/>");
document.writeln("                        <input type=\"hidden\" name=\"c\" value=\"index\"/>");
document.writeln("                        <input type=\"hidden\" name=\"a\" value=\"init\"/>");
document.writeln("                        <input type=\"hidden\" name=\"typeid\" value=\"53\" id=\"typeid\"/>");
document.writeln("                        <input type=\"hidden\" name=\"siteid\" value=\"1\" id=\"siteid\"/>");
document.writeln("                        <input type=\"text\" class=\"text\" name=\"q\" id=\"q\" value=\"输入您想搜索的内容...\" onblur=\"if(this.value==\'\'){this.value=\'输入您想搜索的内容...\'}\" onfocus=\"if (this.value==\'输入您想搜索的内容...\'){this.value=\'\'}\"/>");
document.writeln("                        <a href=\"javascript:document:search.submit();\"  />Search</a>");
document.writeln("                    </form>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </ol>");
document.writeln("    </div>");
document.writeln("    <div class=\"feature\">");
document.writeln("        <ul>");
document.writeln("            <li id=\"ft1\">顾客体系</li>");
document.writeln("            <li id=\"ft2\">术前严检</li>");
document.writeln("            <li id=\"ft3\">医生资质</li>");
document.writeln("            <li id=\"ft4\">材料安全</li>");
document.writeln("            <li id=\"ft5\">设备安全</li>");
document.writeln("            <li id=\"ft6\">手术安全</li>");
document.writeln("            <li id=\"ft7\">术后管理</li>");
document.writeln("            <li id=\"ft8\">承诺保障</li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"copy\">");
document.writeln("    copyright &copy; 2007-2016 nccharm.com.cn 南昌佳美美容医院版权所有 赣ICP备10202890号-10 特别声明：本站内容仅供参考，不作为诊断及医疗依据。");
document.writeln("</div>");
document.writeln("<script type=\"text/javascript\" src=\"http://www.nccharm.com.cn/kst/kst.js\"></script>");
document.writeln("<script type=\"text/javascript\">var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");");
document.writeln("document.write(unescape(\"%3Cscript src=\'\" + _bdhmProtocol + \"hm.baidu.com/h.js%3Ffd7612455142d2b0a7021b84e7db4299\' type=\'text/javascript\'%3E%3C/script%3E\"));</script>");
document.writeln("<script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id=\'cnzz_stat_icon_1253119688\'%3E%3C/span%3E%3Cscript src=\'\" + cnzz_protocol + \"s95.cnzz.com/z_stat.php%3Fid%3D1253119688\' type=\'text/javascript\'%3E%3C/script%3E\"));</script>");
/*手机跳转代码*/
document.writeln("<script>");
document.writeln("    var mobileAgent = new Array(\'iphone\',\'android\',\'mobile\',\'blackberry\', \'webos\', \'incognito\', \'webmate\', \'bada\', \'nokia\', \'lg\', \'ucweb\', \'skyfire\');");
document.writeln("    var browser = navigator.userAgent.toLowerCase();");
document.writeln("    var isMobile = false;");
document.writeln("    for(var i=0; i<mobileAgent.length; i++){");
document.writeln("        if(browser.indexOf(mobileAgent[i])!=-1){");
document.writeln("            isMobile = true;");
document.writeln("            url = window.location.href;");
document.writeln("            str=url.replace(\'www.\',\'wap.\');");
document.writeln("            window.location.href=str;");
document.writeln("            break;");
document.writeln("        }");
document.writeln("    }");
document.writeln("</script>");