document.writeln("<div class=\"head\">");
document.writeln("    <div class=\"head_top\">");
document.writeln("        <div class=\"ww1100\">");
document.writeln("            <div class=\"left\"><b>佳美资质</b>：江西瑞蓝培训注射基地 &nbsp;江西内窥镜技术引进</div>");
document.writeln("            <div class=\"right\"> <a href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\">问答</a> / <a href=\"/pinpai/yisheng/\">医生</a> / <a href=\"/special/\">专题</a> / <a href=\"/pinpai/anli/\">案例</a> / <a href=\"/pinpai/anli/\">真人秀</a> 免费美丽热线：400 679 6066</div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\"head_logo ww1100\">");
document.writeln("        <div class=\"left logo\"><a href=\"/\"><h1>南昌佳美美容医院</h1></a></div>");
document.writeln("        <div class=\"ztty_menu\">");
document.writeln("            <dl class=\"ztty_menu01\">");
document.writeln("                <dt><a href=\"/zhengxing/\" target=\"_blank\">整形美容科</a><br /><span>PLASTIC CENTER</span></dt>");
document.writeln("                <dd>");
document.writeln("                    <div class=\"ztdd\">");
document.writeln("                        <div class=\"rowh\">"); 
document.writeln("                            <a href=\"/special/16ytlx.html\" target=\"_blank\">胸部</a>");
document.writeln("                            <a href=\"/special/16ybzh.html\" target=\"_blank\">眼部</a>");
document.writeln("                            <a href=\"/special/16zhlb.html\" target=\"_blank\">鼻部</a>");
document.writeln("                            <a href=\"/special/15glx.html\" target=\"_blank\">改脸</a>");
document.writeln("                            <a href=\"/special/16jsm.html\" target=\"_blank\">瘦身</a>");
document.writeln("                            <a href=\"/special/16smzx.html\" target=\"_blank\">私密</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"rowh_bot\">");
document.writeln("                            <a href=\"/special/16nkjfx.html\" target=\"_blank\">隆胸</a>");
document.writeln("                            <a href=\"/special/16ybzh.html\" target=\"_blank\">双眼皮</a>");
document.writeln("                            <a href=\"/special/16zhlb.html\" target=\"_blank\">隆鼻</a>");
document.writeln("                            <a href=\"/special/16qyd.html\" target=\"_blank\">祛眼袋</a>");
document.writeln("                            <a href=\"/special/16xz.html\" target=\"_blank\">吸脂</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("");
document.writeln("            <dl class=\"ztty_menu02\">");
document.writeln("                <dt><a href=\"/meifu/\" target=\"_blank\">皮肤美容科</a><br /><span>SKIN CENTER</span></dt>");
document.writeln("                <dd>");
document.writeln("                    <div class=\"ztdd\">");
document.writeln("                        <div class=\"rowh\">");
document.writeln("                            <a href=\"/special/16wzff.html\" target=\"_blank\">嫩肤</a>");
document.writeln("                            <a href=\"/special/16qb.html\" target=\"_blank\">祛斑</a>");
document.writeln("                            <a href=\"/special/16nng.html\" target=\"_blank\">美白</a>");
document.writeln("                            <a href=\"/special/13wx.html\" target=\"_blank\">纹绣</a>");
document.writeln("                            <a href=\"/special/17qtj.html \" target=\"_blank\">祛痣</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"rowh_bot\">");
document.writeln("                            <a href=\"/special/shenlanchuzhou.html\" target=\"_blank\">除皱</a>");
document.writeln("                            <a href=\"/special/16cbtm.html\" target=\"_blank\">脱毛</a>");
document.writeln("                            <a href=\"/special/16qd.html\" target=\"_blank\">祛痘</a>");
document.writeln("                            <a href=\"/special/17qtj.html\" target=\"_blank\">胎记</a>");
document.writeln("                            <a href=\"/special/17qbh.html\" target=\"_blank\">疤痕</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("");
document.writeln("            <dl class=\"ztty_menu03\">");
document.writeln("                <dt><a href=\"/weizhengxing/\" target=\"_blank\">微整形美容科</a><br /><span>INJECTION CENTER</span></dt>");
document.writeln("                <dd>");
document.writeln("                    <div class=\"ztdd\">");
document.writeln("                        <div class=\"rowh\">");
document.writeln("                            <a href=\"/special/15qyd.html\" target=\"_blank\">玻尿酸</a>");
document.writeln("                            <a href=\"/special/16wz.html\" target=\"_blank\">瘦脸针</a>");
document.writeln("                            <a href=\"/special/16wz.html\" target=\"_blank\">年轻化</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"rowh_bot\">");
document.writeln("                            <a href=\"/weizhengxing/rds/\" target=\"_blank\">肉毒素</a>");
document.writeln("                            <a href=\"/weizhengxing/shouxiaotui/\" target=\"_blank\">瘦小腿</a>");
document.writeln("                            <a href=\"/special/16mbxd.html\" target=\"_blank\">注射除皱</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\"ztty_menu04\">");
document.writeln("                <dt><a href=\"/kouqiang/\" target=\"_blank\">口腔美容科</a><br /><span>ORAL CENTER</span></dt>");
document.writeln("                <dd>");
document.writeln("                    <div class=\"ztdd\">");
document.writeln("                        <div class=\"rowh\">");
document.writeln("                            <a href=\"/kouqiang/kaociya/mrgxf/\" target=\"_blank\">全瓷牙</a>");
document.writeln("                            <a href=\"/kouqiang/kaociya/mrgxf/\" target=\"_blank\">仿生美容冠</a>");
document.writeln("                            <a href=\"/special/16yxjz.html\" target=\"_blank\">隐形矫正</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"rowh_bot\">");
document.writeln("                            <a href=\"/special/16yxjz.html\" target=\"_blank\">牙齿正畸</a>");
document.writeln("                            <a href=\"/kouqiang/meibai/lgmb/\" target=\"_blank\">牙齿美白</a>");
document.writeln("                            <a href=\"/kouqiang/zhongzhi/\" target=\"_blank\">种植牙</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
